name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      LATEST_VERSION: "1.21.5"
      INCLUDE_DEVLIBS: "true"
      VERSIONS_TO_BUILD: "1.21.5"

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Create artifact directory structure
        run: |
          mkdir -p artifacts/1.21.5/libs
          cp ./versions/1.21.5/build/libs/*.jar artifacts/1.21.5/libs/ 2>/dev/null || true
          if [ "$INCLUDE_DEVLIBS" = "true" ]; then
            mkdir -p artifacts/1.21.5/devlibs
            cp ./versions/1.21.5/build/devlibs/*.jar artifacts/1.21.5/devlibs/ 2>/dev/null || true
          fi

      - name: Compute hashes
        run: |
          touch artifacts/hashes.txt
          for jar in $(find artifacts -name '*.jar'); do
            sha256sum $jar >> artifacts/hashes.txt
          done

      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: artifacts
