name: Deploy Javadoc

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: 'adopt'
      - name: Generate Javadoc
        run: ./gradlew javadoc
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: javadoc
          clean: true
          folder: versions/1.21.1/build/docs/javadoc
          target-folder: javadoc
